import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import AppContextProvider from '../context/app.context';
// import ym from 'react-yandex-metrika';
// import { YMInitializer } from 'react-yandex-metrika';
// import { Router } from 'next/router';

// Router.events.on('routeChangeComplete', (url: string) => {
//     if (typeof window !== 'undefined') {
//         ym('hit', url);
//     }
// });

export default function App({
    Component,
    pageProps,
    router,
}: AppProps): JSX.Element {
    return (
        <AppContextProvider
            menu={pageProps.menu}
            firstCategory={pageProps.firstCategory}
        >
            <Head>
                <title>Agregator Products</title>
                {/* <link rel='preconnect' href='https://mc.yandex.ru' /> */}
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
                <meta
                    property='og:url'
                    content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath}
                />
                <meta property='og:locale' content='ru_RU' />
                <meta property='og:type' content='article' />
            </Head>
            {/* <YMInitializer
                accounts={[]}
                options={{ webvisor: true, defer: true }}
                version='2'
            /> */}
            <Component {...pageProps} />
        </AppContextProvider>
    );
}
